<?php
use maze\db\Expression;

return [
    'expansion' => [
        [
            'id_exp' => 1,
            'name' => 'admin',
            'id_tmp' => null,
            'time_cache' => 15,
            'enable_cache' => 1,
            'param' => null,
            'enabled' => 1
        ],
        [
            'id_exp' => 2,
            'name' => 'user',
            'id_tmp' => null,
            'time_cache' => 15,
            'enable_cache' => 1,
            'param' => null,
            'enabled' => 1
        ],
        [
            'id_exp' => 3,
            'name' => 'menu',
            'id_tmp' => null,
            'time_cache' => 15,
            'enable_cache' => 1,
            'param' => null,
            'enabled' => 1
        ],
        [
            'id_exp' => 4,
            'name' => 'settings',
            'id_tmp' => null,
            'time_cache' => 15,
            'enable_cache' => 1,
            'param' => null,
            'enabled' => 1
        ],
        [
            'id_exp' => 5,
            'name' => 'templating',
            'id_tmp' => null,
            'time_cache' => 15,
            'enable_cache' => 1,
            'param' => null,
            'enabled' => 1
        ],
        [
            'id_exp' => 6,
            'name' => 'widget',
            'id_tmp' => null,
            'time_cache' => 15,
            'enable_cache' => 1,
            'param' => null,
            'enabled' => 1
        ],
        [
            'id_exp' => 7,
            'name' => 'plugins',
            'id_tmp' => null,
            'time_cache' => 15,
            'enable_cache' => 1,
            'param' => null,
            'enabled' => 1
        ],
        [
            'id_exp' => 8,
            'name' => 'elfinder',
            'id_tmp' => null,
            'time_cache' => 15,
            'enable_cache' => 1,
            'param' => null,
            'enabled' => 1
        ],
        [
            'id_exp' => 9,
            'name' => 'languages',
            'id_tmp' => null,
            'time_cache' => 15,
            'enable_cache' => 1,
            'param' => null,
            'enabled' => 1
        ],
        [
            'id_exp' => 10,
            'name' => 'installapp',
            'id_tmp' => null,
            'time_cache' => 15,
            'enable_cache' => 1,
            'param' => null,
            'enabled' => 1
        ],
        [
            'id_exp' => 11,
            'name' => 'logs',
            'id_tmp' => null,
            'time_cache' => 15,
            'enable_cache' => 1,
            'param' => null,
            'enabled' => 1
        ],
        [
            'id_exp' => 12,
            'name' => 'contents',
            'id_tmp' => null,
            'time_cache' => 15,
            'enable_cache' => 1,
            'param' => null,
            'enabled' => 1
        ],
        [
            'id_exp' => 13,
            'name' => 'dictionary',
            'id_tmp' => null,
            'time_cache' => 15,
            'enable_cache' => 1,
            'param' => null,
            'enabled' => 1
        ]
    ],
    'group_exp'=>[
        [
            'id_group'=>1,
            'name'=>'system',
            'title'=>'LIB_USERINTERFACE_TOOLBAR_GROUP_SYSTEM',
            'icon'=>'/library/image/icon/16/menu/white/icon-settingsthree-gears.png',
            'ordering'=>1,
            'description'=>null
        ],
        [
            'id_group'=>2,
            'name'=>'content',
            'title'=>'LIB_USERINTERFACE_TOOLBAR_GROUP_CONTENT',
            'icon'=>'/library/image/icon/16/computer/white/icon-document.png',
            'ordering'=>2,
            'description'=>null
        ]
    ],
    'install_app'=>[
        [
            'id_app'=>1,
            'type'=>'expansion',
            'name'=>'admin',
            'group_name'=>'system',
            'front_back'=>0,
            'ordering'=>1,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>2,
            'type'=>'expansion',
            'name'=>'user',
            'group_name'=>'system',
            'front_back'=>0,
            'ordering'=>2,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>3,
            'type'=>'expansion',
            'name'=>'user',
            'group_name'=>'system',
            'front_back'=>1,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>4,
            'type'=>'expansion',
            'name'=>'menu',
            'group_name'=>'system',
            'front_back'=>0,
            'ordering'=>3,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>5,
            'type'=>'expansion',
            'name'=>'settings',
            'group_name'=>'system',
            'front_back'=>0,
            'ordering'=>4,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>6,
            'type'=>'expansion',
            'name'=>'templating',
            'group_name'=>'system',
            'front_back'=>0,
            'ordering'=>5,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>7,
            'type'=>'expansion',
            'name'=>'widget',
            'group_name'=>'system',
            'front_back'=>0,
            'ordering'=>6,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>8,
            'type'=>'expansion',
            'name'=>'widget',
            'group_name'=>'system',
            'front_back'=>1,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>9,
            'type'=>'expansion',
            'name'=>'plugins',
            'group_name'=>'system',
            'front_back'=>0,
            'ordering'=>7,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>10,
            'type'=>'expansion',
            'name'=>'elfinder',
            'group_name'=>'system',
            'front_back'=>0,
            'ordering'=>8,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>11,
            'type'=>'expansion',
            'name'=>'languages',
            'group_name'=>'system',
            'front_back'=>0,
            'ordering'=>9,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>12,
            'type'=>'expansion',
            'name'=>'installapp',
            'group_name'=>'system',
            'front_back'=>0,
            'ordering'=>10,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>13,
            'type'=>'expansion',
            'name'=>'logs',
            'group_name'=>'system',
            'front_back'=>0,
            'ordering'=>11,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>14,
            'type'=>'expansion',
            'name'=>'contents',
            'group_name'=>'content',
            'front_back'=>0,
            'ordering'=>12,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>15,
            'type'=>'expansion',
            'name'=>'contents',
            'group_name'=>'content',
            'front_back'=>1,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>16,
            'type'=>'expansion',
            'name'=>'dictionary',
            'group_name'=>'content',
            'front_back'=>0,
            'ordering'=>13,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>17,
            'type'=>'expansion',
            'name'=>'dictionary',
            'group_name'=>'content',
            'front_back'=>1,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>18,
            'type'=>'library',
            'name'=>'framework',
            'group_name'=>null,
            'front_back'=>1,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>19,
            'type'=>'plugin',
            'name'=>'tinymce',
            'group_name'=>null,
            'front_back'=>0,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>20,
            'type'=>'plugin',
            'name'=>'shortcode',
            'group_name'=>null,
            'front_back'=>1,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>21,
            'type'=>'plugin',
            'name'=>'captchaver',
            'group_name'=>null,
            'front_back'=>1,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>22,
            'type'=>'plugin',
            'name'=>'elfinderbtn',
            'group_name'=>null,
            'front_back'=>0,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>23,
            'type'=>'template',
            'name'=>'admintmp',
            'group_name'=>null,
            'front_back'=>0,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>24,
            'type'=>'template',
            'name'=>'defaults',
            'group_name'=>null,
            'front_back'=>1,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>25,
            'type'=>'widget',
            'name'=>'adminlogo',
            'group_name'=>null,
            'front_back'=>0,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>26,
            'type'=>'widget',
            'name'=>'submenu',
            'group_name'=>null,
            'front_back'=>0,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>27,
            'type'=>'widget',
            'name'=>'toolbar',
            'group_name'=>null,
            'front_back'=>0,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>28,
            'type'=>'widget',
            'name'=>'navbar',
            'group_name'=>null,
            'front_back'=>0,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>29,
            'type'=>'widget',
            'name'=>'breadcrumbs',
            'group_name'=>null,
            'front_back'=>0,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>31,
            'type'=>'widget',
            'name'=>'menu',
            'group_name'=>null,
            'front_back'=>1,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>32,
            'type'=>'widget',
            'name'=>'htmlcode',
            'group_name'=>null,
            'front_back'=>1,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>33,
            'type'=>'widget',
            'name'=>'breadcrumb',
            'group_name'=>null,
            'front_back'=>1,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>34,
            'type'=>'widget',
            'name'=>'formsend',
            'group_name'=>null,
            'front_back'=>1,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
        [
            'id_app'=>35,
            'type'=>'library',
            'name'=>'framework',
            'group_name'=>null,
            'front_back'=>0,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ],
    ],
    'plugin'=>[
        [
            'id_plg'=>1,
            'group_name'=>'editor',
            'name'=>'tinymce',
            'ordering'=>1,
            'enabled'=>1,
            'param'=>null
        ],
        [
            'id_plg'=>2,
            'group_name'=>'content',
            'name'=>'shortcode',
            'ordering'=>1,
            'enabled'=>1,
            'param'=>null
        ],
        [
            'id_plg'=>3,
            'group_name'=>'captcha',
            'name'=>'captchaver',
            'ordering'=>1,
            'enabled'=>1,
            'param'=>null
        ],
        [
            'id_plg'=>4,
            'group_name'=>'system',
            'name'=>'elfinderbtn',
            'ordering'=>1,
            'enabled'=>1,
            'param'=>null
        ]
    ],
    "template"=>[
        [
            "id_tmp"=>1,
            "name"=>"admintmp",
            "title"=>"Шаблон админ панели",
            "home"=>1,
            "front"=>0,
            "time_active"=>null,
            "time_inactive"=>null,
            "param"=>null            
        ],
        [
            "id_tmp"=>2,
            "name"=>"defaults",
            "title"=>"Шаблон по умочанию",
            "home"=>1,
            "front"=>1,
            "time_active"=>null,
            "time_inactive"=>null,
            "param"=>null            
        ]
    ],
    "widgets"=>[
        [
           "id_wid"=>1,
            "name"=>"adminlogo",
            "title"=>"Вход в админ панель",
            "position"=>"login",
            "ordering"=>1,
            "time_cache"=>2,
            "enable_cache"=>2,
            "time_active"=>null,
            "time_inactive"=>null,
            "enabled"=>1,
            "enable_php"=>0,
            "php_code"=>null,
            "title_show"=>0,
            "id_tmp"=>1,
            "id_lang"=>0,
            "param"=>null
        ],
        [
           "id_wid"=>2,
            "name"=>"submenu",
            "title"=>"Меню админа боковое",
            "position"=>"left",
            "ordering"=>1,
            "time_cache"=>2,
            "enable_cache"=>2,
            "time_active"=>null,
            "time_inactive"=>null,
            "enabled"=>1,
            "enable_php"=>0,
            "php_code"=>null,
            "title_show"=>0,
            "id_tmp"=>1,
            "id_lang"=>0,
            "param"=>null
        ],
        [
           "id_wid"=>3,
            "name"=>"toolbar",
            "title"=>"Панель инструментов",
            "position"=>"tools",
            "ordering"=>1,
            "time_cache"=>2,
            "enable_cache"=>2,
            "time_active"=>null,
            "time_inactive"=>null,
            "enabled"=>1,
            "enable_php"=>0,
            "php_code"=>null,
            "title_show"=>0,
            "id_tmp"=>1,
            "id_lang"=>0,
            "param"=>null
        ],
        [
           "id_wid"=>4,
            "name"=>"navbar",
            "title"=>"Панель инструментов меню",
            "position"=>"top",
            "ordering"=>1,
            "time_cache"=>2,
            "enable_cache"=>2,
            "time_active"=>null,
            "time_inactive"=>null,
            "enabled"=>1,
            "enable_php"=>0,
            "php_code"=>null,
            "title_show"=>0,
            "id_tmp"=>1,
            "id_lang"=>0,
            "param"=>null
        ],
        [
           "id_wid"=>5,
            "name"=>"breadcrumbs",
            "title"=>"Навигационная цепочка",
            "position"=>"nav",
            "ordering"=>1,
            "time_cache"=>2,
            "enable_cache"=>2,
            "time_active"=>null,
            "time_inactive"=>null,
            "enabled"=>1,
            "enable_php"=>0,
            "php_code"=>"if(RC::app()->request->get('run')){return true;}else{return false;}",
            "title_show"=>0,
            "id_tmp"=>1,
            "id_lang"=>0,
            "param"=>null
        ]
    ],
    "private_rule"=>[
        [
            "name"=>"isUserCreate",
            "exp_name"=>"contents",
            "data"=>'O:50:"admin\expansion\exp_contents\access\CreateUserRule":4:{s:4:"name";s:12:"isUserCreate";s:7:"expName";s:8:"contents";s:9:"createdAt";i:1434092078;s:9:"updatedAt";i:1434092078;}',
            "created_at"=>"1434092078",
            "updated_at"=>"1434092078"
        ]
    ],
    "private"=>[
        [
            "id_priv"=>1,
            "exp_name"=>"admin",
            "name"=>"VIEW_ADMIN",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN",
            "description"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN_DES"
        ],
        [
            "id_priv"=>2,
            "exp_name"=>"admin",
            "name"=>"ADD_DESKTOP",
            "rule_name"=>null,
            "title"=>"EXP_ADMIN_DESSKTOP_ACCESS_ADDEDIT",
            "description"=>null
        ],
        [
            "id_priv"=>3,
            "exp_name"=>"admin",
            "name"=>"DELETE_DESKTOP",
            "rule_name"=>null,
            "title"=>"EXP_ADMIN_DESSKTOP_ACCESS_DELETE",
            "description"=>null
        ],
        [
            "id_priv"=>4,
            "exp_name"=>"admin",
            "name"=>"ADD_GADGET",
            "rule_name"=>null,
            "title"=>"EXP_ADMIN_DESSKTOP_ACCESS_ADDGADGET",
            "description"=>null
        ],
        [
            "id_priv"=>5,
            "exp_name"=>"admin",
            "name"=>"SETTINGS_GADGET",
            "rule_name"=>null,
            "title"=>"EXP_ADMIN_DESSKTOP_ACCESS_SETTINGSGADGET",
            "description"=>null
        ],
        [
            "id_priv"=>6,
            "exp_name"=>"admin",
            "name"=>"DELETE_GADGET",
            "rule_name"=>null,
            "title"=>"EXP_ADMIN_DESSKTOP_ACCESS_DELETEGADGET",
            "description"=>null
        ],
        [
            "id_priv"=>7,
            "exp_name"=>"user",
            "name"=>"VIEW_ADMIN",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN",
            "description"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN_DES"
        ],
        [
            "id_priv"=>8,
            "exp_name"=>"user",
            "name"=>"EDIT_USER",
            "rule_name"=>null,
            "title"=>"EXP_USER_PRIVATE_EDIT_USER",
            "description"=>null
        ],
        [
            "id_priv"=>9,
            "exp_name"=>"user",
            "name"=>"DELET_USER",
            "rule_name"=>null,
            "title"=>"EXP_USER_PRIVATE_DELET_USER",
            "description"=>null
        ],
        [
            "id_priv"=>10,
            "exp_name"=>"user",
            "name"=>"EDIT_ROLE",
            "rule_name"=>null,
            "title"=>"EXP_USER_PRIVATE_EDIT_ROLE",
            "description"=>null
        ],
        [
            "id_priv"=>11,
            "exp_name"=>"user",
            "name"=>"DELET_ROLE",
            "rule_name"=>null,
            "title"=>"EXP_USER_PRIVATE_DELET_ROLE",
            "description"=>null
        ],
        [
            "id_priv"=>12,
            "exp_name"=>"user",
            "name"=>"EDIT_PASS",
            "rule_name"=>null,
            "title"=>"EXP_USER_PRIVATE_EDIT_PASS",
            "description"=>null
        ],
        [
            "id_priv"=>13,
            "exp_name"=>"user",
            "name"=>"VIEW_SESSIONS",
            "rule_name"=>null,
            "title"=>"EXP_USER_PRIVATE_VIEW_SESSIONS",
            "description"=>null
        ],
        [
            "id_priv"=>14,
            "exp_name"=>"user",
            "name"=>"VIEW_ROLE",
            "rule_name"=>null,
            "title"=>"EXP_USER_PRIVATE_VIEW_ROLE",
            "description"=>null
        ],
        [
            "id_priv"=>15,
            "exp_name"=>"user",
            "name"=>"DELETE_SESSIONS",
            "rule_name"=>null,
            "title"=>"EXP_USER_PRIVATE_DELETE_SESSIONS",
            "description"=>null
        ],
        [
            "id_priv"=>16,
            "exp_name"=>"menu",
            "name"=>"VIEW_ADMIN",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN",
            "description"=>null
        ],
        [
            "id_priv"=>17,
            "exp_name"=>"menu",
            "name"=>"EDIT_MENU",
            "rule_name"=>null,
            "title"=>"EXP_MENU_PRIVATE_EDIT_MENU",
            "description"=>null
        ],
        [
            "id_priv"=>18,
            "exp_name"=>"menu",
            "name"=>"DELET_MENU",
            "rule_name"=>null,
            "title"=>"EXP_MENU_PRIVATE_DELET_MENU",
            "description"=>null
        ],
        [
            "id_priv"=>19,
            "exp_name"=>"menu",
            "name"=>"EDIT_ITEM",
            "rule_name"=>null,
            "title"=>"EXP_MENU_PRIVATE_EDIT_ITEM",
            "description"=>null
        ],
        [
            "id_priv"=>20,
            "exp_name"=>"menu",
            "name"=>"DELET_ITEM",
            "rule_name"=>null,
            "title"=>"EXP_MENU_PRIVATE_DELET_ITEM",
            "description"=>null
        ],
        [
            "id_priv"=>21,
            "exp_name"=>"settings",
            "name"=>"VIEW_ADMIN",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN",
            "description"=>null
        ],
        [
            "id_priv"=>22,
            "exp_name"=>"settings",
            "name"=>"EDIT_SYS_PRIVATE",
            "rule_name"=>null,
            "title"=>"EXP_SETTINGS_PRIVATE_EDIT_SYS_PRIVATE",
            "description"=>null
        ],
        [
            "id_priv"=>23,
            "exp_name"=>"settings",
            "name"=>"EDIT_EXP",
            "rule_name"=>null,
            "title"=>"EXP_SETTINGS_PRIVATE_EDIT_EXP",
            "description"=>null
        ],
        [
            "id_priv"=>24,
            "exp_name"=>"settings",
            "name"=>"EDIT_SYS_CONFIG",
            "rule_name"=>null,
            "title"=>"EXP_SETTINGS_PRIVATE_EDIT_SYS_CONFIG",
            "description"=>"EXP_SETTINGS_PRIVATE_EDIT_SYS_CONFIG_DES"
        ],
        [
            "id_priv"=>25,
            "exp_name"=>"settings",
            "name"=>"EDIT_SYS_SERVER",
            "rule_name"=>null,
            "title"=>"EXP_SETTINGS_PRIVATE_EDIT_SYS_SERVER",
            "description"=>null
        ],
        [
            "id_priv"=>26,
            "exp_name"=>"settings",
            "name"=>"CLEAR_CACHE",
            "rule_name"=>null,
            "title"=>"EXP_SETTINGS_PRIVATE_CLEAR_CACHE",
            "description"=>null
        ],
        [
            "id_priv"=>27,
            "exp_name"=>"settings",
            "name"=>"VIEW_EXP",
            "rule_name"=>null,
            "title"=>"EXP_SETTINGS_PRIVATE_VIEW_EXP",
            "description"=>null
        ],
        [
            "id_priv"=>28,
            "exp_name"=>"templating",
            "name"=>"VIEW_ADMIN",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN",
            "description"=>null
        ],
        [
            "id_priv"=>29,
            "exp_name"=>"templating",
            "name"=>"EDIT_STYLE",
            "rule_name"=>null,
            "title"=>"EXP_TEMPLATING_PRIVATE_EDIT_STYLE",
            "description"=>null
        ],
        [
            "id_priv"=>30,
            "exp_name"=>"templating",
            "name"=>"DELET_STYLE",
            "rule_name"=>null,
            "title"=>"EXP_TEMPLATING_PRIVATE_DELET_STYLE",
            "description"=>null
        ],
        [
            "id_priv"=>31,
            "exp_name"=>"templating",
            "name"=>"EDIT_TMP",
            "rule_name"=>null,
            "title"=>"EXP_TEMPLATING_PRIVATE_EDIT_TMP",
            "description"=>null
        ],
        [
            "id_priv"=>32,
            "exp_name"=>"widget",
            "name"=>"VIEW_ADMIN",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN",
            "description"=>null
        ],
        [
            "id_priv"=>33,
            "exp_name"=>"widget",
            "name"=>"EDIT_WIDGET",
            "rule_name"=>null,
            "title"=>"EXP_WIDGET_PRIVATE_EDIT_WIDGET",
            "description"=>null
        ],
        [
            "id_priv"=>34,
            "exp_name"=>"widget",
            "name"=>"DELET_WIDGET",
            "rule_name"=>null,
            "title"=>"EXP_WIDGET_PRIVATE_DELET_WIDGET",
            "description"=>null
        ],
        [
            "id_priv"=>35,
            "exp_name"=>"widget",
            "name"=>"EDIT_WIDGET_ADMIN",
            "rule_name"=>null,
            "title"=>"EXP_WIDGET_PRIVATE_EDIT_WIDGET_ADMIN",
            "description"=>null
        ],
        [
            "id_priv"=>36,
            "exp_name"=>"plugins",
            "name"=>"VIEW_ADMIN",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN",
            "description"=>null
        ],
        [
            "id_priv"=>37,
            "exp_name"=>"plugins",
            "name"=>"EDIT_PLUGIN",
            "rule_name"=>null,
            "title"=>"EXP_PLUGINS_PRIVATE_EDIT_PLUGIN",
            "description"=>null
        ],
        [
            "id_priv"=>38,
            "exp_name"=>"elfinder",
            "name"=>"VIEW_ADMIN",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN",
            "description"=>null
        ],
        [
            "id_priv"=>39,
            "exp_name"=>"elfinder",
            "name"=>"EDIT_PROFILE",
            "rule_name"=>null,
            "title"=>"EXP_ELFINDER_EDIT_PROFILE",
            "description"=>null
        ],
        [
            "id_priv"=>40,
            "exp_name"=>"elfinder",
            "name"=>"DELETE_PROFILE",
            "rule_name"=>null,
            "title"=>"EXP_ELFINDER_DELETE_PROFILE",
            "description"=>null
        ],
        [
            "id_priv"=>41,
            "exp_name"=>"elfinder",
            "name"=>"VIEW_PATH",
            "rule_name"=>null,
            "title"=>"EXP_ELFINDER_VIEW_PATH",
            "description"=>null
        ],
        [
            "id_priv"=>42,
            "exp_name"=>"elfinder",
            "name"=>"EDIT_PATH",
            "rule_name"=>null,
            "title"=>"EXP_ELFINDER_EDIT_PATH",
            "description"=>null
        ],
        [
            "id_priv"=>43,
            "exp_name"=>"elfinder",
            "name"=>"DELETE_PATH",
            "rule_name"=>null,
            "title"=>"EXP_ELFINDER_DELETE_PATH",
            "description"=>null
        ],
        [
            "id_priv"=>44,
            "exp_name"=>"languages",
            "name"=>"VIEW_ADMIN",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN",
            "description"=>null
        ],
        [
            "id_priv"=>45,
            "exp_name"=>"languages",
            "name"=>"EDIT_LANG",
            "rule_name"=>null,
            "title"=>"EXP_LANGUAGES_PRIVATE_EDIT_LANG",
            "description"=>null
        ],
        [
            "id_priv"=>46,
            "exp_name"=>"languages",
            "name"=>"DELET_LANG",
            "rule_name"=>null,
            "title"=>"EXP_LANGUAGES_PRIVATE_DELET_LANG",
            "description"=>null
        ],
        [
            "id_priv"=>47,
            "exp_name"=>"languages",
            "name"=>"VIEW_LANG_APP",
            "rule_name"=>null,
            "title"=>"EXP_LANGUAGES_PRIVATE_VIEW_LANG_APP",
            "description"=>null
        ],
        [
            "id_priv"=>48,
            "exp_name"=>"languages",
            "name"=>"EDIT_LANG_APP",
            "rule_name"=>null,
            "title"=>"EXP_LANGUAGES_PRIVATE_EDIT_LANG_APP",
            "description"=>null
        ],
        [
            "id_priv"=>49,
            "exp_name"=>"languages",
            "name"=>"DELET_LANG_APP",
            "rule_name"=>null,
            "title"=>"EXP_LANGUAGES_PRIVATE_DELET_LANG_APP",
            "description"=>null
        ],
        [
            "id_priv"=>50,
            "exp_name"=>"languages",
            "name"=>"VIEW_LANG_PACKS",
            "rule_name"=>null,
            "title"=>"EXP_LANGUAGES_PRIVATE_VIEW_LANG_PACKS",
            "description"=>null
        ],
        [
            "id_priv"=>51,
            "exp_name"=>"languages",
            "name"=>"EDIT_LANG_PACKS",
            "rule_name"=>null,
            "title"=>"EXP_LANGUAGES_PRIVATE_EDIT_LANG_PACKS",
            "description"=>null
        ],
        [
            "id_priv"=>52,
            "exp_name"=>"languages",
            "name"=>"DELET_LANG_PACKS",
            "rule_name"=>null,
            "title"=>"EXP_LANGUAGES_PRIVATE_DELET_LANG_PACKS",
            "description"=>null
        ],
        [
            "id_priv"=>53,
            "exp_name"=>"languages",
            "name"=>"VIEW_LANG_OVERLOAD",
            "rule_name"=>null,
            "title"=>"EXP_LANGUAGES_PRIVATE_VIEW_LANG_OVERLOAD",
            "description"=>null
        ],
        [
            "id_priv"=>54,
            "exp_name"=>"languages",
            "name"=>"EDIT_LANG_OVERLOAD",
            "rule_name"=>null,
            "title"=>"EXP_LANGUAGES_PRIVATE_EDIT_LANG_OVERLOAD",
            "description"=>null
        ],
        [
            "id_priv"=>55,
            "exp_name"=>"languages",
            "name"=>"DELET_LANG_OVERLOAD",
            "rule_name"=>null,
            "title"=>"EXP_LANGUAGES_PRIVATE_DELET_LANG_OVERLOAD",
            "description"=>null
        ],
        [
            "id_priv"=>56,
            "exp_name"=>"installapp",
            "name"=>"VIEW_ADMIN",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN",
            "description"=>null
        ],
        [
            "id_priv"=>57,
            "exp_name"=>"installapp",
            "name"=>"DELET_APP",
            "rule_name"=>null,
            "title"=>"EXP_INSTALLAPP_PRIVATE_DELET_APP",
            "description"=>null
        ],
        [
            "id_priv"=>58,
            "exp_name"=>"installapp",
            "name"=>"INSTALL_APP",
            "rule_name"=>null,
            "title"=>"EXP_INSTALLAPP_PRIVATE_INSTALL_APP",
            "description"=>null
        ],
        [
            "id_priv"=>59,
            "exp_name"=>"logs",
            "name"=>"VIEW_ADMIN",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN",
            "description"=>null
        ],
        [
            "id_priv"=>60,
            "exp_name"=>"system",
            "name"=>"LOGIN_ADMIN",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_PRIVATE_LOGIN_ADMIN",
            "description"=>"LIB_FRAMEWORK_EXPANSION_PRIVATE_LOGIN_ADMIN_DES"
        ],
        [
            "id_priv"=>61,
            "exp_name"=>"system",
            "name"=>"VIEW_STYLE",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_PRIVATE_VIEW_STYLE",
            "description"=>null
        ],
        [
            "id_priv"=>62,
            "exp_name"=>"system",
            "name"=>"VIEW_TEMPLATE",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_PRIVATE_VIEW_TEMPLATE",
            "description"=>null
        ],
        [
            "id_priv"=>63,
            "exp_name"=>"system",
            "name"=>"VIEW_POSITION",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_PRIVATE_VIEW_POSITION",
            "description"=>null
        ],
        [
            "id_priv"=>64,
            "exp_name"=>"system",
            "name"=>"ROOT",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_PRIVATE_ROOT",
            "description"=>null
        ],
        [
            "id_priv"=>65,
            "exp_name"=>"system",
            "name"=>"VIEW_SITEDISABLE",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_PRIVATE_VIEW_SITEDISABLE",
            "description"=>null
        ],
        [
            "id_priv"=>66,
            "exp_name"=>"system",
            "name"=>"VIEW_TOOLBAR",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_PRIVATE_VIEW_TOOLBAR",
            "description"=>null
        ],
        [
            "id_priv"=>67,
            "exp_name"=>"contents",
            "name"=>"VIEW_ADMIN",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN",
            "description"=>null
        ],
        [
            "id_priv"=>68,
            "exp_name"=>"contents",
            "name"=>"EDIT_CONTENTS",
            "rule_name"=>null,
            "title"=>"EXP_CONTENTS_ACCESS_EDIT_CONTENTS",
            "description"=>null
        ],
        [
            "id_priv"=>69,
            "exp_name"=>"contents",
            "name"=>"DELETE_CONTENTS",
            "rule_name"=>null,
            "title"=>"EXP_CONTENTS_ACCESS_DELETE_CONTENTS",
            "description"=>null
        ],
        [
            "id_priv"=>70,
            "exp_name"=>"contents",
            "name"=>"EDIT_SELF_CONTENTS",
            "rule_name"=>"isUserCreate",
            "title"=>"EXP_CONTENTS_ACCESS_EDIT_SELF_CONTENTS",
            "description"=>null
        ],
        [
            "id_priv"=>71,
            "exp_name"=>"contents",
            "name"=>"DELETE_SELF_CONTENTS",
            "rule_name"=>"isUserCreate",
            "title"=>"EXP_CONTENTS_ACCESS_DELETE_SELF_CONTENTS",
            "description"=>null
        ],
        [
            "id_priv"=>72,
            "exp_name"=>"contents",
            "name"=>"EDIT_HOME_CONTENTS",
            "rule_name"=>null,
            "title"=>"EXP_CONTENTS_ACCESS_EDIT_HOME_CONTENTS",
            "description"=>null
        ],
        [
            "id_priv"=>73,
            "exp_name"=>"contents",
            "name"=>"EDIT_TYPE_CONTENTS",
            "rule_name"=>null,
            "title"=>"EXP_CONTENTS_ACCESS_EDIT_TYPE_CONTENTS",
            "description"=>null
        ],
        [
            "id_priv"=>74,
            "exp_name"=>"contents",
            "name"=>"DELETE_TYPE_CONTENTS",
            "rule_name"=>null,
            "title"=>"EXP_CONTENTS_ACCESS_DELETE_TYPE_CONTENTS",
            "description"=>null
        ],
        [
            "id_priv"=>75,
            "exp_name"=>"contents",
            "name"=>"EDIT_FIELD_CONTENTS",
            "rule_name"=>null,
            "title"=>"EXP_CONTENTS_ACCESS_EDIT_FIELD_CONTENTS",
            "description"=>null
        ],
        [
            "id_priv"=>76,
            "exp_name"=>"contents",
            "name"=>"DELETE_FIELD_CONTENTS",
            "rule_name"=>null,
            "title"=>"EXP_CONTENTS_ACCESS_DELETE_FIELD_CONTENTS",
            "description"=>null
        ],
        [
            "id_priv"=>77,
            "exp_name"=>"contents",
            "name"=>"EDIT_VIEW_CONTENTS",
            "rule_name"=>null,
            "title"=>"EXP_CONTENTS_ACCESS_EDIT_VIEW_CONTENTS",
            "description"=>null
        ],
        [
            "id_priv"=>78,
            "exp_name"=>"dictionary",
            "name"=>"VIEW_ADMIN",
            "rule_name"=>null,
            "title"=>"LIB_FRAMEWORK_EXPANSION_VIEW_ADMIN",
            "description"=>null
        ],
        [
            "id_priv"=>79,
            "exp_name"=>"dictionary",
            "name"=>"EDIT_DICTIONARY",
            "rule_name"=>null,
            "title"=>"EXP_DICTIONARY_ACCESS_EDIT_DICTIONARY",
            "description"=>null
        ],
        [
            "id_priv"=>80,
            "exp_name"=>"dictionary",
            "name"=>"DELETE_DICTIONARY",
            "rule_name"=>null,
            "title"=>"EXP_DICTIONARY_ACCESS_DELETE_DICTIONARY",
            "description"=>null
        ],
        [
            "id_priv"=>81,
            "exp_name"=>"dictionary",
            "name"=>"EDIT_TERM",
            "rule_name"=>null,
            "title"=>"EXP_DICTIONARY_ACCESS_EDIT_TERM",
            "description"=>null
        ],
        [
            "id_priv"=>82,
            "exp_name"=>"dictionary",
            "name"=>"DELETE_TERM",
            "rule_name"=>null,
            "title"=>"EXP_DICTIONARY_ACCESS_DELETE_TERM",
            "description"=>null
        ],
        [
            "id_priv"=>83,
            "exp_name"=>"dictionary",
            "name"=>"EDIT_FIELD",
            "rule_name"=>null,
            "title"=>"EXP_DICTIONARY_ACCESS_EDIT_FIELD",
            "description"=>null
        ],
        [
            "id_priv"=>84,
            "exp_name"=>"dictionary",
            "name"=>"DELETE_FIELD",
            "rule_name"=>null,
            "title"=>"EXP_DICTIONARY_ACCESS_DELETE_FIELD",
            "description"=>null
        ],
        [
            "id_priv"=>85,
            "exp_name"=>"user",
            "name"=>"EDIT_SELF_USER",
            "rule_name"=>null,
            "title"=>"EXP_USER_PRIVATE_EDIT_SELF_USER",
            "description"=>null
        ]
    ],
    "roles"=>[
        [
            "id_role"=>1,
            "name"=>"Администратор",
            "description"=>null
        ],
        [
            "id_role"=>2,
            "name"=>"Пользователь",
            "description"=>null
        ]
    ],
    "role_private"=>[
        [
            "id_role"=>1,
            "id_priv"=>1,
        ],
        [
            "id_role"=>1,
            "id_priv"=>2,
        ],
        [
            "id_role"=>1,
            "id_priv"=>3,
        ],
        [
            "id_role"=>1,
            "id_priv"=>4,
        ],
        [
            "id_role"=>1,
            "id_priv"=>5,
        ],
        [
            "id_role"=>1,
            "id_priv"=>6,
        ],
        [
            "id_role"=>1,
            "id_priv"=>7,
        ],
        [
            "id_role"=>1,
            "id_priv"=>8,
        ],
        [
            "id_role"=>1,
            "id_priv"=>9,
        ],
        [
            "id_role"=>1,
            "id_priv"=>10,
        ],
        [
            "id_role"=>1,
            "id_priv"=>11,
        ],
        [
            "id_role"=>1,
            "id_priv"=>12,
        ],
        [
            "id_role"=>1,
            "id_priv"=>13,
        ],
        [
            "id_role"=>1,
            "id_priv"=>14,
        ],
        [
            "id_role"=>1,
            "id_priv"=>15,
        ],
        [
            "id_role"=>1,
            "id_priv"=>16,
        ],
        [
            "id_role"=>1,
            "id_priv"=>17,
        ],
        [
            "id_role"=>1,
            "id_priv"=>18,
        ],
        [
            "id_role"=>1,
            "id_priv"=>19,
        ]
        ,
        [
            "id_role"=>1,
            "id_priv"=>20,
        ],
        [
            "id_role"=>1,
            "id_priv"=>21,
        ],
        [
            "id_role"=>1,
            "id_priv"=>22,
        ],
        [
            "id_role"=>1,
            "id_priv"=>23,
        ],
        [
            "id_role"=>1,
            "id_priv"=>24,
        ],
        [
            "id_role"=>1,
            "id_priv"=>25,
        ],
        [
            "id_role"=>1,
            "id_priv"=>26,
        ],
        [
            "id_role"=>1,
            "id_priv"=>27,
        ],
        [
            "id_role"=>1,
            "id_priv"=>28,
        ],
        [
            "id_role"=>1,
            "id_priv"=>29,
        ],
        [
            "id_role"=>1,
            "id_priv"=>30,
        ],
        [
            "id_role"=>1,
            "id_priv"=>31,
        ],
        [
            "id_role"=>1,
            "id_priv"=>32,
        ],
        [
            "id_role"=>1,
            "id_priv"=>33,
        ],
        [
            "id_role"=>1,
            "id_priv"=>34,
        ],
        [
            "id_role"=>1,
            "id_priv"=>35,
        ],
        [
            "id_role"=>1,
            "id_priv"=>36,
        ],
        [
            "id_role"=>1,
            "id_priv"=>37,
        ],
        [
            "id_role"=>1,
            "id_priv"=>38,
        ],
        [
            "id_role"=>1,
            "id_priv"=>39,
        ],
        [
            "id_role"=>1,
            "id_priv"=>40,
        ],
        [
            "id_role"=>1,
            "id_priv"=>41,
        ],
        [
            "id_role"=>1,
            "id_priv"=>42,
        ],
        [
            "id_role"=>1,
            "id_priv"=>43,
        ],
        [
            "id_role"=>1,
            "id_priv"=>44,
        ],
        [
            "id_role"=>1,
            "id_priv"=>45,
        ],
        [
            "id_role"=>1,
            "id_priv"=>46,
        ],
        [
            "id_role"=>1,
            "id_priv"=>47,
        ],
        [
            "id_role"=>1,
            "id_priv"=>48,
        ],
        [
            "id_role"=>1,
            "id_priv"=>49,
        ],
        [
            "id_role"=>1,
            "id_priv"=>50,
        ],
        [
            "id_role"=>1,
            "id_priv"=>51,
        ],
        [
            "id_role"=>1,
            "id_priv"=>52,
        ],
        [
            "id_role"=>1,
            "id_priv"=>53,
        ],
        [
            "id_role"=>1,
            "id_priv"=>54,
        ],
        [
            "id_role"=>1,
            "id_priv"=>55,
        ],
        [
            "id_role"=>1,
            "id_priv"=>56,
        ],
        [
            "id_role"=>1,
            "id_priv"=>57,
        ],
        [
            "id_role"=>1,
            "id_priv"=>58,
        ],
        [
            "id_role"=>1,
            "id_priv"=>59,
        ],
        [
            "id_role"=>1,
            "id_priv"=>60,
        ],
        [
            "id_role"=>1,
            "id_priv"=>61,
        ],
        [
            "id_role"=>1,
            "id_priv"=>62,
        ],
        [
            "id_role"=>1,
            "id_priv"=>63,
        ],
        [
            "id_role"=>1,
            "id_priv"=>64,
        ],
        [
            "id_role"=>1,
            "id_priv"=>65,
        ],
        [
            "id_role"=>1,
            "id_priv"=>66,
        ],
        [
            "id_role"=>1,
            "id_priv"=>67,
        ],
        [
            "id_role"=>1,
            "id_priv"=>68,
        ],
        [
            "id_role"=>1,
            "id_priv"=>69,
        ],
        [
            "id_role"=>1,
            "id_priv"=>70,
        ],
        [
            "id_role"=>1,
            "id_priv"=>71,
        ],
        [
            "id_role"=>1,
            "id_priv"=>72,
        ],
        [
            "id_role"=>1,
            "id_priv"=>73,
        ],
        [
            "id_role"=>1,
            "id_priv"=>74,
        ],
        [
            "id_role"=>1,
            "id_priv"=>75,
        ],
        [
            "id_role"=>1,
            "id_priv"=>76,
        ],
        [
            "id_role"=>1,
            "id_priv"=>77,
        ],
        [
            "id_role"=>1,
            "id_priv"=>78,
        ],
        [
            "id_role"=>1,
            "id_priv"=>79,
        ],
        [
            "id_role"=>1,
            "id_priv"=>80,
        ],
        [
            "id_role"=>1,
            "id_priv"=>81,
        ],
        [
            "id_role"=>1,
            "id_priv"=>82,
        ],
        [
            "id_role"=>1,
            "id_priv"=>83,
        ],
        [
            "id_role"=>1,
            "id_priv"=>84,
        ]
    ],
    "users"=>function($db, $table, $install){
        $db->createCommand()->insert('{{%' . $table . '}}', [
            'id_user'=>1,
            'username'=>$install->accountModel->username,
            'name'=>$install->accountModel->username,
            'avatar'=>null,
            'email'=>$install->accountModel->email,
            'password'=> md5($install->accountModel->password),
            'registerDate'=>new Expression("NOW()"),
            'lastvisitDate'=>null,
            'timeactiv'=>null,
            'keyactiv'=>null,
            'id_lang'=>0,
            'timezone'=>null,
            'editor_admin'=>null,
            'editor_site'=>null,
            'status'=>0,
            'bloc'=>0,
        ])->execute(); 
    },
    "user_roles"=>[
        [
            "id_role"=>1,
            "id_user"=>1
        ]
    ],
    "languages"=>function($db, $table, $install){
        $db->createCommand()->insert('{{%' . $table . '}}', [
            'id_lang'=>1,
            'lang_code'=>$install->langModel->lang_code,
            'title'=>$install->langModel->title,
            'reduce'=>$install->langModel->reduce,
            'img'=>$install->langModel->img,
            'ordering'=>1,
            'enabled'=>$install->langModel->enabled
        ])->execute();
        
        $db->createCommand()->insert('{{%install_app}}', [
            'type'=>'languages',
            'name'=>$install->langModel->lang_code,
            'group_name'=>null,
            'front_back'=>0,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ])->execute();
        
        
        $db->createCommand()->insert('{{%install_app}}', [
            'type'=>'languages',
            'name'=>$install->langModel->lang_code,
            'group_name'=>null,
            'front_back'=>1,
            'ordering'=>0,
            'install_data'=>new Expression("NOW()")
        ])->execute(); 
        
        $ext = $db->createCommand('SELECT * FROM {{%install_app}}')->queryAll();
        
        foreach($ext as $ex){
            $db->createCommand()->insert('{{%lang_app}}', [
                'id_lang'=>1,
                'id_app'=>$ex['id_app'],
                'defaults'=>1,
                'ordering'=>0,
                'enabled'=>1
            ])->execute(); 
        }
    }        
];
